; Please do not edit this file! If this file is modified, results are unpredictable.
; Instead of modifying this file, simply create a new MEGA Analysis Options file by using the MEGA Prototyper.
[ MEGAinfo ]
ver                                = 7170509-x86_64 Linux              
[ DataSettings ]
datatype                           = snNucleotide                      
containsCodingNuc                  = False                             
MissingBaseSymbol                  = ?                                 
IdenticalBaseSymbol                = .                                 
GapSymbol                          = -                                 
[ ProcessTypes ]
ppDistEst                          = true                              
ppPairTaxa                         = true                              
[ AnalysisSettings ]
Analysis                           = Distance Estimation               
Scope                              = Pairs of taxa                     
Estimate Variance                  = ====================              
Variance Estimation Method         = None                              
No. of Bootstrap Replications      = Not Applicable                    
Substitution Model                 = ====================              
Substitutions Type                 = Nucleotide                        
Model/Method                       = Kimura 2-parameter model          
Substitutions to Include           = d: Transitions + Transversions    
Rates and Patterns                 = ====================              
Rates among Sites                  = Gamma Distributed (G)             
Gamma Parameter                    = 1.00                              
Pattern among Lineages             = Same (Homogeneous)                
Data Subset to Use                 = ====================              
Gaps/Missing Data Treatment        = Complete deletion                 
Site Coverage Cutoff (%)           = Not Applicable                    
Has Time Limit                     = False                             
Maximum Execution Time             = -1                                
