#!/usr/bin/env python3
"""
Generated by Claude.

draw_gene.py — Gene-structure PDF visualization

从 GFF3 文件（1 个基因 / 1 个 mRNA）绘制基因结构图，支持叠加彩色元件。

用法
----
  draw_gene.py GENE.gff3 <bp>:<label> [选项]

必需参数
--------
  GENE.gff3          GFF3 文件，仅含 1 个基因 / 1 个 mRNA。
                     必需 feature：CDS。
                     可选 feature：five_prime_UTR / three_prime_UTR
                       （也识别 5'UTR / UTR5 / 5UTR 等别名）。
  <bp>:<label>       标尺长度及标签，如 1000:1Kb 或 500:500bp。

可选参数
--------
  -e ELEMENTS        元件 TSV（制表符分隔，无表头），4 列：
                       seq_name  start  end  color
                     seq_name 为染色体名或 GFF3 中 mRNA 的 ID。
                     坐标 1-based；mRNA 坐标从转录本 5' 端起算。
  -o OUTPUT          输出 PDF（默认 output.pdf）。
  --name NAME        基因标签（覆盖 GFF3 Name/ID 属性）。
  --cds-color HEX    CDS 框默认填充色（默认 #4CAF50）。
  --fig-width  W     图宽（英寸），默认自动。
  --fig-height H     图高（英寸），默认 2.2。
"""

import argparse
import re
import sys

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches


# ── GFF3 解析 ────────────────────────────────────────────────────────────────

_UTR5 = {'five_prime_utr', "5'utr", 'utr5', '5utr', 'fiveprimeutr'}
_UTR3 = {'three_prime_utr', "3'utr", 'utr3', '3utr', 'threeprimeutr'}


def _parse_attrs(s):
    d = {}
    for tok in s.split(';'):
        tok = tok.strip()
        if '=' in tok:
            k, v = tok.split('=', 1)
            d[k.strip()] = v.strip()
    return d


def parse_gff3(path):
    """返回 (gene, mrna, cds_list, utr5_list, utr3_list)。"""
    gene = mrna = None
    cds, utr5, utr3 = [], [], []
    with open(path) as fh:
        for raw in fh:
            if raw.startswith('#') or not raw.strip():
                continue
            cols = raw.rstrip('\n').split('\t')
            if len(cols) < 9:
                continue
            seqname, _, feat, start, end, _, strand, _, attr_s = cols
            rec = dict(seqname=seqname, start=int(start), end=int(end),
                       strand=strand, attrs=_parse_attrs(attr_s))
            fl = feat.lower().replace('_', '')
            if fl == 'gene':
                gene = rec
            elif fl in ('mrna', 'transcript'):
                mrna = rec
            elif fl == 'cds':
                cds.append(rec)
            elif fl in _UTR5 or feat.lower() in _UTR5:
                utr5.append(rec)
            elif fl in _UTR3 or feat.lower() in _UTR3:
                utr3.append(rec)
    for lst in (cds, utr5, utr3):
        lst.sort(key=lambda r: r['start'])
    return gene, mrna, cds, utr5, utr3


# ── 元件解析 & mRNA→基因组坐标转换 ──────────────────────────────────────────

def parse_elements(path):
    if not path:
        return []
    elems = []
    with open(path) as fh:
        for raw in fh:
            raw = raw.strip()
            if not raw or raw.startswith('#'):
                continue
            cols = raw.split('\t')
            if len(cols) < 4:
                continue
            elems.append(dict(seq_name=cols[0], start=int(cols[1]),
                              end=int(cols[2]), color=cols[3].strip()))
    return elems


def _exons_5to3(all_recs, strand):
    """按 mRNA 5'→3' 顺序返回 (start, end) 列表（已去重排序）。"""
    exons = sorted({(r['start'], r['end']) for r in all_recs},
                   key=lambda x: x[0])
    return list(reversed(exons)) if strand == '-' else exons


def _mrna_to_genomic(pos, exons_5to3, strand):
    """将 1-based mRNA 位置映射到基因组坐标。"""
    cum = 0
    for gs, ge in exons_5to3:
        elen = ge - gs + 1
        if cum + elen >= pos:
            off = pos - cum - 1            # 0-based exon 内偏移
            return (ge - off) if strand == '-' else (gs + off)
        cum += elen
    return None                            # 超出范围


def _mrna_elem_to_segments(mrna_s, mrna_e, exons_5to3, strand):
    """将 mRNA 坐标区间拆分为若干基因组片段（逐外显子切割，跳过内含子）。"""
    segments = []
    cum = 0
    for gs, ge in exons_5to3:
        elen = ge - gs + 1
        ex_ms = cum + 1          # 该外显子在 mRNA 上的起始位置（1-based）
        ex_me = cum + elen       # 该外显子在 mRNA 上的终止位置
        ov_s  = max(mrna_s, ex_ms)
        ov_e  = min(mrna_e, ex_me)
        if ov_s <= ov_e:
            off_s = ov_s - cum - 1   # 0-based 外显子内偏移
            off_e = ov_e - cum - 1
            if strand == '-':
                segments.append((ge - off_e, ge - off_s))
            else:
                segments.append((gs + off_s, gs + off_e))
        cum += elen
        if cum >= mrna_e:
            break
    return segments


def resolve_elements(raw_elems, chrom, mrna_id, strand, all_recs):
    """将元件坐标统一转为基因组坐标；mRNA 坐标跨内含子时按外显子分段。"""
    exons = _exons_5to3(all_recs, strand)
    out = []
    for e in raw_elems:
        sn = e['seq_name']
        if sn == chrom:
            out.append(e)
        elif sn == mrna_id:
            for (g_s, g_e) in _mrna_elem_to_segments(
                    e['start'], e['end'], exons, strand):
                out.append(dict(seq_name=chrom,
                                start=g_s, end=g_e,
                                color=e['color']))
    return out


# ── 绘图辅助函数 ──────────────────────────────────────────────────────────────

def _dash_intron(ax, x1, x2, y0, lw):
    """在 x1-x2 之间绘制黑色虚线（内含子）。"""
    if x2 <= x1 + 1:
        return
    ax.plot([x1, x2], [y0, y0], color='black', lw=lw,
            linestyle='--', dashes=(4, 3), solid_capstyle='butt', zorder=2)


def _box(ax, x, y_c, w, h, fc, ec='none', lw=0.5, zo=3):
    """绘制矩形框，y_c 为垂直中心。"""
    if w <= 0:
        return
    ax.add_patch(mpatches.Rectangle(
        (x, y_c - h / 2), w, h,
        linewidth=lw, edgecolor=ec, facecolor=fc, zorder=zo))


# ── 主绘图逻辑 ────────────────────────────────────────────────────────────────

def draw_figure(ax, cds, utr5, utr3, elements,
                x0, x1, strand,
                gene_label, cds_color, scale_bp, scale_label):

    Y0    = 0.0      # 基线 y 坐标
    CDS_H = 0.38     # CDS 框高
    UTR_H = 0.20     # UTR 框高
    LW    = 1.2      # 线宽

    span = x1 - x0

    # 合并所有外显子坐标，用于检测内含子间隙
    exon_set = sorted({(r['start'], r['end'])
                       for r in cds + utr5 + utr3}, key=lambda x: x[0])

    # ── 内含子（相邻外显子间黑色虚线） ─────────────────────────────
    for i in range(len(exon_set) - 1):
        is_ = exon_set[i][1]          # 当前外显子末端
        ie  = exon_set[i + 1][0]     # 下一外显子起始
        if ie > is_ + 1:
            _dash_intron(ax, is_, ie, Y0, LW)

    # ── UTR 框（窄，白底有边框） ─────────────────────────────────────
    for r in utr5 + utr3:
        _box(ax, r['start'], Y0, r['end'] - r['start'], UTR_H,
             fc='white', ec='#555555', lw=0.8, zo=3)

    # ── CDS 框 ───────────────────────────────────────────────────────
    for r in cds:
        _box(ax, r['start'], Y0, r['end'] - r['start'], CDS_H,
             fc=cds_color, ec='none', lw=0, zo=3)

    # ── 叠加元件（UTR 区域用 UTR_H，CDS 区域用 CDS_H） ───────────────
    utr_ranges = [(r['start'], r['end']) for r in utr5 + utr3]
    for e in elements:
        in_utr = any(e['start'] <= ue and e['end'] >= us
                     for us, ue in utr_ranges)
        h = UTR_H if in_utr else CDS_H
        _box(ax, e['start'], Y0, e['end'] - e['start'], h,
             fc=e['color'], ec='none', lw=0, zo=4)

    # ── 标尺（右上角） ───────────────────────────────────────────────
    sb_margin = span * 0.01
    sb_x2 = x1 - sb_margin
    sb_x1 = sb_x2 - scale_bp
    sb_y  = 0.58
    cap_h = 0.04
    ax.plot([sb_x1, sb_x2], [sb_y, sb_y],
            color='black', lw=2, solid_capstyle='butt')
    for bx in (sb_x1, sb_x2):
        ax.plot([bx, bx], [sb_y - cap_h, sb_y + cap_h],
                color='black', lw=2)
    ax.text((sb_x1 + sb_x2) / 2, sb_y + 0.08, scale_label,
            ha='center', va='bottom', fontsize=9, fontweight='bold')

    # ── 基因标签（左上角） ───────────────────────────────────────────
    lx = x0 + span * 0.005
    ax.text(lx, 0.62, gene_label,
            ha='left', va='bottom', fontsize=11, fontweight='bold')

    # ── 方向箭头（"start"） ──────────────────────────────────────────
    arr_len = scale_bp * 0.30
    arr_y   = 0.44
    if strand == '+':
        ax_s, ax_e = lx, lx + arr_len
    else:
        ax_s, ax_e = lx + arr_len, lx
    ax.annotate('', xy=(ax_e, arr_y), xytext=(ax_s, arr_y),
                arrowprops=dict(arrowstyle='->', color='blue', lw=1.4))
    ax.text((ax_s + ax_e) / 2, arr_y + 0.05, 'start',
            ha='center', va='bottom', fontsize=8, color='blue')

    # ── 坐标轴设置 ───────────────────────────────────────────────────
    ax.set_xlim(x0, x1)
    ax.set_ylim(-0.52, 0.88)
    ax.axis('off')


# ── 入口 ──────────────────────────────────────────────────────────────────────

def main():
    ap = argparse.ArgumentParser(
        description='Gene-structure PDF from GFF3.',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__)
    ap.add_argument('gff3',  help='GFF3 文件（1 个基因，1 个 mRNA）')
    ap.add_argument('scale', help='标尺  <bp>:<标签>  如 1000:1Kb')
    ap.add_argument('-e', '--elements', default=None,
                    help='元件 TSV（seq_name  start  end  color）')
    ap.add_argument('-o', '--output',   default='output.pdf',
                    help='输出 PDF（默认 output.pdf）')
    ap.add_argument('--name',       default=None,
                    help='基因标签（覆盖 GFF3 Name/ID）')
    ap.add_argument('--cds-color',  default='#4CAF50',
                    help='CDS 默认填充色（默认 #4CAF50）')
    ap.add_argument('--fig-width',  type=float, default=None,
                    help='图宽（英寸），默认自动')
    ap.add_argument('--fig-height', type=float, default=2.2,
                    help='图高（英寸），默认 2.2')
    ap.add_argument('--xmin', type=int, default=None,
                    help='绘图起始坐标（基因组坐标，1-based）；优先于自动推断')
    ap.add_argument('--xmax', type=int, default=None,
                    help='绘图终止坐标（基因组坐标，1-based）；优先于自动推断')
    args = ap.parse_args()

    # 解析标尺参数
    m = re.fullmatch(r'(\d+):(.+)', args.scale)
    if not m:
        sys.exit(f'标尺格式错误 "{args.scale}"，应为 <bp>:<label>，如 1000:1Kb')
    scale_bp    = int(m.group(1))
    scale_label = m.group(2)

    # 解析 GFF3
    gene, mrna, cds, utr5, utr3 = parse_gff3(args.gff3)
    if not cds:
        sys.exit('GFF3 中未找到 CDS 特征。')

    chrom   = (gene or mrna or cds[0])['seqname']
    strand  = cds[0]['strand']
    mrna_id = None
    if mrna:
        mrna_id = mrna['attrs'].get('ID') or mrna['attrs'].get('Name')

    # 确定基因标签：优先用 mRNA ID，其次 gene Name/ID
    gene_label = args.name
    if not gene_label and mrna_id:
        gene_label = mrna_id
    if not gene_label:
        for rec in (gene, mrna):
            if rec:
                gene_label = rec['attrs'].get('Name') or rec['attrs'].get('ID')
                if gene_label:
                    break
    gene_label = gene_label or 'Gene'

    # 解析并转换元件坐标
    raw_elems = parse_elements(args.elements)
    elements  = resolve_elements(raw_elems, chrom, mrna_id, strand,
                                 cds + utr5 + utr3)

    # 计算绘图范围
    if args.xmin is not None and args.xmax is not None:
        # 用户指定起止坐标：直接使用，不再自动扩展
        x0, x1 = args.xmin, args.xmax
    else:
        coords = ([r['start'] for r in cds + utr5 + utr3] +
                  [r['end']   for r in cds + utr5 + utr3])
        for rec in (gene, mrna):
            if rec:
                coords += [rec['start'], rec['end']]
        for e in elements:
            coords += [e['start'], e['end']]
        raw_s, raw_e = min(coords), max(coords)
        pad = max(scale_bp * 0.05, (raw_e - raw_s) * 0.02)
        x0  = raw_s - pad
        x1  = raw_e + pad + scale_bp * 0.18   # 右侧留出标尺空间

    # 图幅尺寸
    total = x1 - x0
    fw = args.fig_width or max(8.0, min(28.0, total / scale_bp * 1.0))

    fig, ax = plt.subplots(figsize=(fw, args.fig_height))
    draw_figure(ax, cds, utr5, utr3, elements,
                x0, x1, strand,
                gene_label, args.cds_color, scale_bp, scale_label)
    plt.tight_layout(pad=0.2)
    plt.savefig(args.output, format='pdf', bbox_inches='tight')
    plt.close()
    print(f'已保存 → {args.output}')


if __name__ == '__main__':
    main()
